openapi: 3.2.0
info:
  version: 1.0.0
  x-logo:
    url: https://developers.unqork.io/unqork-logo.png
    backgroundColor: '#FFFFFF'
  title: Unqork Customer Transforms API
  description: Unqork's customer REST API, based on open standards, allows you to set and retrieve module submission data, as well as control other aspects of your Unqork environment.
servers:
- url: https://{host}/api/1.0
  variables:
    host:
      default: env.unqork.io
      description: Environment host
security:
- OAuth2: []
tags:
- name: Transforms
  description: The following endpoints are available to "Administrator" users only.
paths:
  /modules/{moduleId}/transforms:
    get:
      tags:
      - Transforms
      summary: Get Transforms
      operationId: getTransforms
      description: 'Returns transform objects. This is a paged endpoint (see Paging).

        ### Authorization Required:

        - Application View'
      parameters:
      - $ref: '#/components/parameters/ModuleID'
      - name: limit
        in: query
        description: Maximum number of results to return (default 50, maximum 1000)
        required: false
        schema:
          type: integer
          format: int32
          default: 50
          maximum: 1000
      responses:
        '200':
          description: Transforms
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TransformResponse'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
      - Transforms
      summary: Create Transform
      operationId: createTransform
      description: 'Creates a new transform.

        ### Authorization Required:

        - Application Create'
      parameters:
      - $ref: '#/components/parameters/ModuleID'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransformPost'
      responses:
        '201':
          description: Transform created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransformResponse'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /modules/{moduleId}/transforms/{transformName}:
    get:
      tags:
      - Transforms
      summary: Get Transform
      operationId: getTransform
      description: 'Returns a transform object based on a module ID and transform name.

        ### Authorization Required:

        - Application View'
      parameters:
      - $ref: '#/components/parameters/ModuleID'
      - name: transformName
        in: path
        description: Name of transform
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Transform
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransformResponse'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
      - Transforms
      summary: Update Transform
      operationId: updateTransform
      description: 'Updates a single transform.

        ### Authorization Required:

        - Application Update'
      parameters:
      - $ref: '#/components/parameters/ModuleID'
      - name: transformName
        in: path
        description: Name of transform to update
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransformPut'
      responses:
        '200':
          description: Transform updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransformResponse'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
      - Transforms
      summary: Delete Transform
      operationId: deleteTransform
      description: 'Deletes a transform based on the transform name supplied.

        ### Authorization Required:

        - Application Delete'
      parameters:
      - $ref: '#/components/parameters/ModuleID'
      - name: transformName
        in: path
        description: Name of transform to delete
        required: true
        schema:
          type: string
      responses:
        '204':
          description: Transform deleted
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  parameters:
    ModuleID:
      name: moduleId
      in: path
      description: Unique module ID
      required: true
      schema:
        type: string
  schemas:
    Error:
      type: object
      description: Error
      required:
      - code
      - message
      properties:
        code:
          description: HTTP status code
          type: integer
          format: int32
          enum:
          - 400
          - 401
          - 403
          - 404
          - 412
          - 500
        message:
          description: Error message
          type: string
    TransformResponse:
      type: object
      required:
      - name
      - moduleId
      - type
      - io
      properties:
        name:
          type: string
        moduleId:
          type: string
        type:
          type: string
          enum:
          - njk-xml
          - njk-pdf
          - njk
          - xsl
        io:
          type: string
          enum:
          - in
          - out
        template:
          type: string
    TransformPost:
      type: object
      required:
      - name
      - type
      - io
      properties:
        name:
          type: string
          description: Can only contain alphanumerics and hyphens
        type:
          type: string
          enum:
          - njk-xml
          - njk-pdf
          - njk-txt
          - njk
          - xsl
        io:
          type: string
          enum:
          - in
          - out
        template:
          type: string
    TransformPut:
      type: object
      required:
      - name
      properties:
        name:
          type: string
          description: Can only contain alphanumerics and hyphens
        type:
          type: string
          enum:
          - njk-xml
          - njk-pdf
          - njk-txt
          - njk
          - xsl
        io:
          type: string
          enum:
          - in
          - out
        template:
          type: string
  securitySchemes:
    OAuth2:
      description: "The Unqork API implements the [OAuth 2.0 Client Credentials Grant](https://datatracker.ietf.org/doc/html/rfc6749#section-1.3.4) and the [OAuth 2.0 Password Grant](https://tools.ietf.org/html/rfc6749#section-1.3.3). Access via OAuth2 Client Credentials Grant can be utilized by creating Client Credentials through the API Access Management Administration page. Access via OAuth2 Password Grant can be enabled for all users in Environment Administration. Once OAuth2 Password Grant is enabled, all Unqork users can use their Unqork username/password to retrieve an access token.\n\nIn order to utilize any of the API resources, you must first retrieve an access token by POSTing your credentials to the access token URL, e.g. using `curl`:\n```\n  $ curl -u '{clientId}:{clientSecret}' -X POST --basic https://xyzfinancial.unqork.io/api/1.0/oauth2/access_token -d \"grant_type=client_credentials\"\n```\nOr:\n```\n  $ curl -X POST https://xyzfinancial.unqork.io/api/1.0/oauth2/access_token -d \"grant_type=password&username={username}&password={password}\"\n```\nThis returns an \"access_token\", which you would then retain and use in any subsequent resource requests. **Access tokens expire after one hour, at which point you must retrieve a new one.** The access token should be included in a request header:\n```\n  $ curl -H \"Authorization: Bearer {access_token}\" https://xyzfinancial.unqork.io/api/1.0/{endpoint}\n```\n"
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://xyzfinancial.unqork.io/api/1.0/oauth2/access_token
          scopes:
            none: N/A
        password:
          tokenUrl: https://xyzfinancial.unqork.io/api/1.0/oauth2/access_token
          scopes:
            none: N/A
