openapi: 3.2.0
info:
  version: 1.0.0
  x-logo:
    url: https://developers.unqork.io/unqork-logo.png
    backgroundColor: '#FFFFFF'
  title: Unqork Customer Global Variables API
  description: Unqork's customer REST API, based on open standards, allows you to set and retrieve module submission data, as well as control other aspects of your Unqork environment.
servers:
- url: https://{host}/api/1.0
  variables:
    host:
      default: env.unqork.io
      description: Environment host
security:
- OAuth2: []
tags:
- name: Global Variables
paths:
  /globalvars:
    get:
      tags:
      - Global Variables
      summary: Get Global Variables
      operationId: promoteGlobalVariables
      description: 'Returns Global Variables objects.

        ### Authorization Required:

        - Designer Administrator'
      responses:
        '200':
          description: Global Variables
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GlobalVariable'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
      - Global Variables
      summary: Create Global Variables
      operationId: createGlobalVariable
      description: 'Creates a new Global Variable. ''key'' needs to be unique.

        ### Authorization Required:

        - Designer Administrator'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GlobalVariablePost'
      responses:
        '201':
          description: Global Variable created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GlobalVariable'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /globalvars/{globalVariableId}:
    get:
      tags:
      - Global Variables
      summary: Get Global Variable
      operationId: getGlobalVariable
      description: 'Returns a global variable object based on a global variable Id.

        ### Authorization Required:

        - Designer Administrator'
      parameters:
      - name: globalVariableId
        in: path
        description: Id of global variable to retrieve
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Global Variable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GlobalVariable'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      tags:
      - Global Variables
      summary: Update Global Variable
      operationId: updateGlobalVariable
      description: 'Updates a single global variable. ''key'' needs to be unique. Partial updates are supported.

        ### Authorization Required:

        - Designer Administrator'
      parameters:
      - name: globalVariableId
        in: path
        description: Id of global variable to update
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GlobalVariablePatch'
      responses:
        '200':
          description: Global Variable updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GlobalVariable'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
      - Global Variables
      summary: Delete Global Variable
      operationId: deleteGlobalVariable
      description: 'Soft deletes a single global variable.

        ### Authorization Required:

        - Designer Administrator'
      parameters:
      - name: globalVariableId
        in: path
        description: Id of global variable to delete
        required: true
        schema:
          type: string
      responses:
        '204':
          description: Global Variable deleted
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    GlobalVariablePatch:
      type: object
      properties:
        key:
          type: string
          description: Name of the key of the global variable
        value:
          type: string
          description: Value of the key of the global variable
        description:
          type: string
          description: Description for the global variable
        serverSideOnly:
          type: boolean
          description: Whether the global variable is available server side only
    GlobalVariable:
      type: object
      properties:
        id:
          type: string
          description: Id of the global variable
        key:
          type: string
          description: Name of the key of the global variable
        value:
          type: string
          description: Value of the key of the global variable
        description:
          type: string
          description: Description for the global variable
        serverSideOnly:
          type: boolean
          description: Whether the global variable is available server side only
        created:
          type: string
          format: date-time
        createdBy:
          type: string
          description: Creator of the global variable
        modified:
          type: string
          format: date-time
        modifiedBy:
          type: string
          description: Last modifier of the global variable
        deleted:
          type: string
          format: date-time
    GlobalVariablePost:
      type: object
      required:
      - key
      properties:
        key:
          type: string
          description: Name of the key of the global variable
        value:
          type: string
          description: Value of the key of the global variable
        description:
          type: string
          description: Description for the global variable
        serverSideOnly:
          type: boolean
          description: Whether the global variable is available server side only
    Error:
      type: object
      description: Error
      required:
      - code
      - message
      properties:
        code:
          description: HTTP status code
          type: integer
          format: int32
          enum:
          - 400
          - 401
          - 403
          - 404
          - 412
          - 500
        message:
          description: Error message
          type: string
  securitySchemes:
    OAuth2:
      description: "The Unqork API implements the [OAuth 2.0 Client Credentials Grant](https://datatracker.ietf.org/doc/html/rfc6749#section-1.3.4) and the [OAuth 2.0 Password Grant](https://tools.ietf.org/html/rfc6749#section-1.3.3). Access via OAuth2 Client Credentials Grant can be utilized by creating Client Credentials through the API Access Management Administration page. Access via OAuth2 Password Grant can be enabled for all users in Environment Administration. Once OAuth2 Password Grant is enabled, all Unqork users can use their Unqork username/password to retrieve an access token.\n\nIn order to utilize any of the API resources, you must first retrieve an access token by POSTing your credentials to the access token URL, e.g. using `curl`:\n```\n  $ curl -u '{clientId}:{clientSecret}' -X POST --basic https://xyzfinancial.unqork.io/api/1.0/oauth2/access_token -d \"grant_type=client_credentials\"\n```\nOr:\n```\n  $ curl -X POST https://xyzfinancial.unqork.io/api/1.0/oauth2/access_token -d \"grant_type=password&username={username}&password={password}\"\n```\nThis returns an \"access_token\", which you would then retain and use in any subsequent resource requests. **Access tokens expire after one hour, at which point you must retrieve a new one.** The access token should be included in a request header:\n```\n  $ curl -H \"Authorization: Bearer {access_token}\" https://xyzfinancial.unqork.io/api/1.0/{endpoint}\n```\n"
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://xyzfinancial.unqork.io/api/1.0/oauth2/access_token
          scopes:
            none: N/A
        password:
          tokenUrl: https://xyzfinancial.unqork.io/api/1.0/oauth2/access_token
          scopes:
            none: N/A
