openapi: 3.2.0
info:
  version: 1.0.0
  x-logo:
    url: https://developers.unqork.io/unqork-logo.png
    backgroundColor: '#FFFFFF'
  title: Unqork Customer Search Configs API
  description: Unqork's customer REST API, based on open standards, allows you to set and retrieve module submission data, as well as control other aspects of your Unqork environment.
servers:
- url: https://{host}/api/1.0
  variables:
    host:
      default: env.unqork.io
      description: Environment host
security:
- OAuth2: []
tags:
- name: Search Configs
paths:
  /searchConfigs/{queryId}/execute:
    post:
      x-unqork-service: true
      tags:
      - Search Configs
      summary: Execute a Query
      description: 'Requires "enable-search-service-for-query" feature flag. Must be an administrator or super-user to use this endpoint. Executes a Query to return records.

        ### Authorization Required:

        - Express Super User or Designer Administrator'
      parameters:
      - $ref: '#/components/parameters/QueryId'
      - name: countOnly
        in: query
        description: Only return the number of records that match the search parameters. These options override the options set in the query itself
        schema:
          type: boolean
      - name: limit
        in: query
        description: Number of records to return. Default and max limit of 50. These options override the options set in the query itself.
        schema:
          type: integer
      - name: offset
        in: query
        description: Number of records to skip before selecting records. Offset is zero based. These options override the options set in the query itself.
        schema:
          type: integer
      - name: sort
        in: query
        description: Name of the field(s) to sort on and the sort direction, can be 1 (ascending) or -1 (descending), separated by a semi-colon. Multiple fields are separated by a comma. Ex. '?firstName:-1,lastName:1'. These options override the options set in the query itself
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                type: string
                description: Variable declared in VQB can be passed here as property
              example:
                variable1: variableValue1
                variable2: variableValue2
      responses:
        '201':
          description: Array of records matching the query
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfModelRecords'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      operationId: postSearchConfigsByQueryIdExecute
      x-operation-id-source: derived
components:
  parameters:
    QueryId:
      name: queryId
      in: path
      description: Unique Query ID
      required: true
      schema:
        type: string
  schemas:
    Error:
      type: object
      description: Error
      required:
      - code
      - message
      properties:
        code:
          description: HTTP status code
          type: integer
          format: int32
          enum:
          - 400
          - 401
          - 403
          - 404
          - 412
          - 500
        message:
          description: Error message
          type: string
    ModelRecord:
      type: object
      properties:
        id:
          type: string
          description: Id of Model Record
        data:
          type: object
          description: Data Model data stored in Model Record
        owner:
          type: string
          description: Owner of Data Model Record
        created:
          type: string
          description: Timestamp of Model Record creation
        archived:
          type: boolean
          default: false
          description: Whether or not the Model Record has been archived
    ArrayOfModelRecords:
      type: array
      items:
        $ref: '#/components/schemas/ModelRecord'
  securitySchemes:
    OAuth2:
      description: "The Unqork API implements the [OAuth 2.0 Client Credentials Grant](https://datatracker.ietf.org/doc/html/rfc6749#section-1.3.4) and the [OAuth 2.0 Password Grant](https://tools.ietf.org/html/rfc6749#section-1.3.3). Access via OAuth2 Client Credentials Grant can be utilized by creating Client Credentials through the API Access Management Administration page. Access via OAuth2 Password Grant can be enabled for all users in Environment Administration. Once OAuth2 Password Grant is enabled, all Unqork users can use their Unqork username/password to retrieve an access token.\n\nIn order to utilize any of the API resources, you must first retrieve an access token by POSTing your credentials to the access token URL, e.g. using `curl`:\n```\n  $ curl -u '{clientId}:{clientSecret}' -X POST --basic https://xyzfinancial.unqork.io/api/1.0/oauth2/access_token -d \"grant_type=client_credentials\"\n```\nOr:\n```\n  $ curl -X POST https://xyzfinancial.unqork.io/api/1.0/oauth2/access_token -d \"grant_type=password&username={username}&password={password}\"\n```\nThis returns an \"access_token\", which you would then retain and use in any subsequent resource requests. **Access tokens expire after one hour, at which point you must retrieve a new one.** The access token should be included in a request header:\n```\n  $ curl -H \"Authorization: Bearer {access_token}\" https://xyzfinancial.unqork.io/api/1.0/{endpoint}\n```\n"
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://xyzfinancial.unqork.io/api/1.0/oauth2/access_token
          scopes:
            none: N/A
        password:
          tokenUrl: https://xyzfinancial.unqork.io/api/1.0/oauth2/access_token
          scopes:
            none: N/A
